### PR TITLE
feat: add check for encryption at rest for Elasticsearch domains

### PR DESCRIPTION
**Pull request by ttacon**
This PR adds a few new AWS checks for a few best practices on Elasticsearch domains. I'd love for these to be included, let me know your thoughts @liamg! Specifically, it checks for the these blocks:

```hcl
encrypt_at_rest {
    enabled = true
}
``` 

```hcl
node_to_node_encryption {
    enabled = true
}
```

```hcl
domain_endpoint_options {
    enforce_https = true
}
```

### CODE REVIEW

**Comment by reedloden** [comment]
Perhaps also check the TLS protocol version? Ensuring that at least TLS 1.2 is used. Not sure if there's a good way outside of checking to see if TLS 1.0 is selected (and warning on that)?

**Comment by reedloden** [comment]
> Perhaps also check the TLS protocol version? Ensuring that at least TLS 1.2 is used. Not sure if there's a good way outside of checking to see if TLS 1.0 is selected (and warning on that)?

Specifically, DomainEndpointOptions TLSSecurityPolicy should be set to something other than `Policy-Min-TLS-1-0-2019-07` (which is the default).

**Comment by reedloden** [comment]
Fixes https://github.com/liamg/tfsec/issues/34

**Comment by ttacon** [comment]
For sure! I almost wonder if that should be a separate check? In my mind, there are two things we're checking on:

 - Is HTTPS enforced?
 - Is a security cipher suite enabled?

In my mind, in particular as the latter one will evolve over time, I feel that it would be better as another check. I can add one next week to this PR.

**Comment by reedloden** [comment]
Agreed, separate check is fine. Just pointing it out since you were working
on this particular resource.

**Comment by ttacon** [comment]
Absolutely! Adding that check makes a ton of sense.

**Review by liamg — APPROVED** [review]
Thank you @ttacon :+1:

**Pull request merged**
