### PR TITLE
Add Dockerfile for Docker support

### PR DESCRIPTION
**Pull request by wesley-dean-flexion**
This commit includes the introduction of a Dockerfile so that the user
may build a Docker image containing tfsec so that it may be run without
having to install it on the host system.

To build:

```sh
docker build -t tfsec .
```

To run:

```sh
docker run --rm -it -v "$(pwd):/workdir" tfsec .
```

### CODE REVIEW

**Comment by liamg** [comment]
Thanks @wesley-dean-flexion - this is awesome!

Would you mind adding the equivalent of the PR summary to the README so people are aware this is available?

Cheers!

**Comment by wesley-dean-flexion** [comment]
Yeah, not a problem!  Give a few minutes and I'll have something pushed.

**Comment by wesley-dean-flexion** [comment]
@liamg  Done!

**Comment by wesley-dean-flexion** [comment]
@liamg oh, also, my markdown linter threw back a few warnings about lines being too long, so I modified the lines that were called out.  I hope you don't mind.

**Pull request merged**
